### ISSUE TITLE
Trying to recreate the getting started example and get a 401

### ISSUE THREAD

**Issue by Kyjor** [MrRefactoring/trello.js#10]
![image](https://user-images.githubusercontent.com/13784123/134070640-c26c91d0-3d20-4f62-b8a2-f66a8f807338.png)

I feel like I am missing something. I got an api key as well as an api token and am getting a 401. The request doesn't even seem like it's trying to use them.

**Comment by MrRefactoring** [comment]
Hi @Kyjor! Can you please show me network response please?

**Comment by Kyjor** [comment]
Hi @MrRefactoring  that was fast! I assume you mean this?
![image](https://user-images.githubusercontent.com/13784123/134071481-00cb351e-dac5-4f97-8900-10e522edabe2.png)
It says invalid key, but I'm using the value from: https://trello.com/app-key
Am I supposed to get it from somewhere else? Thanks!

**Comment by MrRefactoring** [comment]
I will try to issue a new token for myself and test some API endpoints

**Comment by MrRefactoring** [comment]
It's worked for me.

Do you use key from https://trello.com/app-key and token from here:
<img width="667" alt="Снимок экрана 2021-09-20 в 23 51 49" src="https://user-images.githubusercontent.com/10329528/134074092-f0ba4622-3f86-46a1-9853-8ee4950eed5e.png">
?

**Comment by Kyjor** [comment]
Yeah I did. I'm using electron though, and now I'm thinking that might be causing the issue.

**Comment by MrRefactoring** [comment]
I can try to help you if you send me you electron template (you can send it to my email: mrrefactoring@yandex.ru). And don’t forget remove sensitive stuff 😉

**Comment by Kyjor** [comment]
Preparing it now. I am grabbing the boilerplate I started with and adding trello.js. Thanks!

**Comment by Kyjor** [comment]
That example that you sent worked for me! Thank you!
