### ISSUE TITLE
Doesn't support nested resources

### ISSUE THREAD

**Issue by sunlanterns** [MrRefactoring/trello.js#14]
Was using this package because I really liked how straightforward it is to use since it lines up pretty one-to-one with Trello's documentation.

Unfortunately it doesn't appear to support nested resources on any of the calls which is a shame. 

For example, 
https://developer.atlassian.com/cloud/trello/rest/api-group-boards/#api-boards-id-memberships-get
https://developer.atlassian.com/cloud/trello/guides/rest-api/nested-resources/

boards.getBoard should support cards as a nested resource, which means being able to specify things like cardAttachments, and cardFields, but that doesn't seem to be possible here.

**Comment by MrRefactoring** [comment]
So... yeah. I didn't update lib a long time. Looks like I need to do it. I'll try to update.

Thank you for using and claiming problems

**Comment by MrRefactoring** [comment]
Hi @sunlanterns!

I think I fixed it in `v1.2.0`. Please let me know if anything went wrong
